import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";

export const metadata: Metadata={title:"Mobile Mechanic Coverage | Romsey, South Hampshire & Dorset",description:"INDGE Services is based in Romsey and provides mobile servicing, diagnostics and repairs across South Hampshire, the New Forest and into Dorset."};

export default function AreasPage(){return <main>
<PageHero eyebrow="Areas we cover" title="We come to you." accent="Across the region." copy="Based in Romsey, INDGE Services provides mobile servicing, diagnostics and repairs across South Hampshire, the New Forest and into Dorset."/>

<section className="section"><div className="shell coverage-page areas-map-layout"><div><p className="section-label">Our working area</p><h2>Romsey at the centre. A much wider reach.</h2><p className="section-copy">Our working area extends west towards Bournemouth and Poole, east towards Gosport and north towards Winchester, with Southampton and the New Forest forming a core part of the area we serve.</p><p className="section-copy">How far we travel depends on the work required, journey and availability. Tell us where the vehicle is and what it needs and we can confirm whether the job is suitable.</p></div><div className="map-real map-feature"><div className="map-outline"/><b className="pin romsey">Romsey</b><span className="pin poole">Poole</span><span className="pin gosport">Gosport</span><span className="pin winchester">Winchester</span><span className="pin southampton">Southampton</span><span className="map-caption">South Hampshire · New Forest · Dorset</span></div></div></section>

<section className="section compact"><div className="shell area-bands"><article><p className="section-label">Core area</p><h2>Close to home.</h2><p>Romsey, Southampton, Test Valley and the New Forest sit at the heart of our mobile operation.</p></article><article><p className="section-label">Further afield</p><h2>The right job can take us further.</h2><p>We also travel west towards Bournemouth and Poole, east towards Gosport and north towards Winchester for suitable work.</p></article></div></section>

<section className="section"><div className="shell"><div className="intro-grid"><div><p className="section-label">Where we work</p><h2>Vehicle care that fits around your day.</h2></div><p className="section-copy">Mobile work needs a safe, suitable place around the vehicle. For many jobs that can be your driveway, private parking or an appropriate workplace location.</p></div><div className="location-cards work-location-cards"><article><span>01</span><h3>At home</h3><p>A driveway or suitable private parking can become the workspace for servicing, diagnostics and many repairs.</p></article><article><span>02</span><h3>At work</h3><p>For suitable jobs and locations, work can often be carried out while you get on with your working day.</p></article><article><span>03</span><h3>Vehicle immobile?</h3><p>For appropriate diagnostic and repair work, the vehicle does not necessarily need to reach a garage before fault finding can begin.</p></article></div></div></section>

<section className="section mobile-benefit"><div className="shell split"><div><p className="section-label">Why mobile?</p><h2>Your driveway can be the workshop.</h2><p className="section-copy">A substantial amount of routine servicing, diagnostic work and mechanical repair can be carried out where the vehicle is, provided the location and job are suitable.</p><div className="benefit-lines"><span>No garage drop-off.</span><span>No arranging a lift home.</span><span>Professional help comes to the vehicle.</span></div></div><div className="quote-panel"><p className="section-label">Not sure if we cover you?</p><h2>Send us your postcode.</h2><p>Tell us where the vehicle is and what it needs. We will confirm whether the location and work are suitable before booking.</p><Link className="btn btn-primary" href="/quote">Check your location →</Link></div></div></section>

<section className="section compact"><div className="shell area-services"><div><p className="section-label">What travels with us</p><h2>More than a call-out.</h2><p>Our mobile model covers planned servicing, proper fault finding and a broad range of mechanical repairs.</p></div><div className="area-service-links"><Link href="/services/servicing">Servicing <span>→</span></Link><Link href="/services/diagnostics">Diagnostics <span>→</span></Link><Link href="/services/repairs-maintenance">Repairs & maintenance <span>→</span></Link></div></div></section>

<section className="cta"><div className="shell cta-inner"><h2>Tell us where you are.<br/><span>We’ll tell you if we can help.</span></h2><Link className="btn btn-primary" href="/quote">Get a quote →</Link></div></section>
</main>}
